# Лабортаорная работа №1
## 
### Задание №1

In [223]:
print("Hello, World!")

Hello, World!


### Задание №2:
####  Написать генератор случайных матриц(многомерных), который принимает
#### опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
#### матрицы, а min_lim и max_lim - минимальное и максимальное значение для
#### генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
#### значения:
#### m = 50
#### n = 50
#### min_limit = -250
#### max_limit = 1000 + (номер своего варианта)


In [224]:
import numpy as np
m = 100
n = 100
min_limit = -250
max_limit = 1000
array = np.random.randint(min_limit, max_limit, (m, n))
print(array)

[[-172    4  178 ...  599 -211  200]
 [ 557  -51  319 ...  226  305  664]
 [ 460 -114  352 ...  566  445 -184]
 ...
 [ 785  392  632 ...  233   91  700]
 [ 146  499  874 ...  650  841  972]
 [ 198   57  444 ...  634  -13  526]]


### Задание №3:
#### Реализовать методы сортировки строк числовой матрицы в соответствии с
#### заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
#### временем стандартной функции сортировки. Испытания проводить на сгенерированных
#### матрицах.


#### Создание матрицы:

In [225]:
import numpy as np
import time
import math

m = 100
n = 100
min_limit = -250
max_limit = 1000
array = np.random.randint(min_limit, max_limit, (m, n))

time_results = {}

#### Сортировка выбором:

In [226]:
def selectionsort (arr):
    for z in range (len(arr)):
        for i in range (len(arr)-1):
            minimum = i
            for j in range (i+1,len(arr)):
                if arr[z, j] < arr[z, minimum]:
                    minimum = j
            arr[z, i], arr[z, minimum] = arr[z, minimum], arr[z, i]
    return arr

#### Сортировка обменом (пузырьковая)

In [227]:
def swapsort (arr):
    for z in range (len(arr)):
        for i in range (len(arr)-1):
            for j in range (n-i-1):
                if (arr[z, j] > arr[z, j+1]):
                    arr[z, j], arr[z, j+1] = arr[z, j+1], arr[z, j]
    return arr

#### Сортировка вставкой

In [228]:
def insertionsort (arr):
    for z in range (len(arr)):
        for i in range (1, len(arr)):
            element = arr[z, i]
            j = i-1
            while j>=0 and element < arr[z, j]:
                arr[z, j+1] = arr[z, j]
                j -=1
            arr[z, j+1] = element
    return arr

#### Cортировка Шелла

In [229]:
def shellsort(arr):
    for z in range (len(arr)):
        a = len(arr)//2
        while a > 0:
            for i in range (a, len(arr)):
                temp = arr[z, i]
                j = i
                while j >= a and arr[z, j - a] > temp:
                     arr[z, j] = array[z, j - a]
                     j -= a
                arr[z, j] = temp
            a //= 2
    return arr

#### Быстрая сортировка

In [230]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    else:
        q = arr[0]
        less = []
        equal = []
        more = []
        for i in arr:
            if i < q:
                less.append(i)
            elif i > q:
                more.append(i)
            else:
                equal.append(i)
        return quicksort(less) + equal + quicksort(more)

#### Пирамидальная сортировка

In [231]:
def heapsort(arr):
    for i in range (len(arr)//2 - 1, -1, -1):
        heapify(arr, i, len(arr))
    for i in range(len(arr) - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        heapify(arr, 0, i)
    return arr

def heapify (arr, i, s):
    left = 2*i+1
    right = 2*i+2
    if left < s and arr[left] > arr[i]:
        largest = left
    else:
        largest = i
    if right < s and arr[right] > arr[i]:
        largest = right
    if (largest != i):
        arr[largest], arr[i] = arr[i], arr[largest]
        heapify(arr, i, s)

#### Турнирная сортировка 

In [232]:
def build(A, B, x, l, r):
    if l == r:
        B[x] = (A[l], x)
    else:
        mid = (l + r)//2
        build (A, B, 2 * x, l, mid)
        build (A, B, (2 * x) + 1, mid + 1, r)
        if B[(2 * x) + 1][0] < B[2 * x][0]:
            B[x] = B[(2 * x) + 1]
        else:
            B[x] = B[2 * x]
            
def pop(B):
    result = B[1][0]
    index = B[1][1]
    B[index] = None
    while index > 1:
        index //=2
        if B[index * 2] is None:
            minimum = B[(index * 2) + 1]
        elif B[(index * 2) + 1] is None:
            minimum = B[index * 2]
        else:
            minimum = min(B[index * 2], B[(index * 2) + 1])
        if minimum == B[index]:
            break
        B[index] = minimum
    return result

def turn(arr):
    temp = [None] * (2 ** (math.ceil(math.log2(len(arr))) + 1))
    build(arr, temp, 1, 0, len(arr) - 1)
    arr_result = [pop(temp) for _ in range (len(arr))]
    return arr_result

In [233]:
#Отсчёт времени и вывод результатов сортировки выбором
matrix_copy = array.copy()
start_time = time.time_ns() 
selectionsort(matrix_copy)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Выбором=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  265186600 ns 
 Преобразованная матрица: 
 [[-250 -244 -239 ...  974  985  990]
 [-234 -223 -216 ...  987  992  995]
 [-229 -220 -193 ...  953  962  970]
 ...
 [-247 -238 -205 ...  982  990  998]
 [-243 -238 -220 ...  944  950  972]
 [-208 -207 -198 ...  962  985  994]]


In [234]:
#Отсчёт времени и вывод результатов сортировки обменом
matrix_copy = array.copy()
start_time = time.time_ns() 
selectionsort(matrix_copy)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Обменом=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  243176200 ns 
 Преобразованная матрица: 
 [[-250 -244 -239 ...  974  985  990]
 [-234 -223 -216 ...  987  992  995]
 [-229 -220 -193 ...  953  962  970]
 ...
 [-247 -238 -205 ...  982  990  998]
 [-243 -238 -220 ...  944  950  972]
 [-208 -207 -198 ...  962  985  994]]


In [235]:
#Отсчёт времени и вывод результатов сортировки вставкой
matrix_copy = array.copy()
start_time = time.time_ns() 
selectionsort(matrix_copy)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Вставкой=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  250175300 ns 
 Преобразованная матрица: 
 [[-250 -244 -239 ...  974  985  990]
 [-234 -223 -216 ...  987  992  995]
 [-229 -220 -193 ...  953  962  970]
 ...
 [-247 -238 -205 ...  982  990  998]
 [-243 -238 -220 ...  944  950  972]
 [-208 -207 -198 ...  962  985  994]]


In [236]:
#Отсчёт времени и вывод результатов сортировки Шелла
matrix_copy = array.copy()
start_time = time.time_ns() 
selectionsort(matrix_copy)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Шелла=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  229178100 ns 
 Преобразованная матрица: 
 [[-250 -244 -239 ...  974  985  990]
 [-234 -223 -216 ...  987  992  995]
 [-229 -220 -193 ...  953  962  970]
 ...
 [-247 -238 -205 ...  982  990  998]
 [-243 -238 -220 ...  944  950  972]
 [-208 -207 -198 ...  962  985  994]]


In [237]:
#Отсчёт времени и вывод результатов пирамидальной сортировки
matrix_copy = array.copy()
start_time = time.time_ns() 
for i, s in enumerate(matrix_copy):
    matrix_copy[i] = heapsort(s)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Пирамидальная=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  45030300 ns 
 Преобразованная матрица: 
 [[-250 -244  974 ...  386  927  990]
 [-234 -223  992 ...  597  970  995]
 [-229 -220  953 ...  667  962  970]
 ...
 [-247 -238  935 ...  445  923  998]
 [-243 -238  944 ...  433  950  972]
 [-208 -207  985 ...  334  905  994]]


In [238]:
#Отсчёт времени и вывод результатов быстрой сортировки
matrix_copy = array.copy()
start_time = time.time_ns() 
for i, s in enumerate(matrix_copy):
    matrix_copy[i] = quicksort(s)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Быстрая=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  18011600 ns 
 Преобразованная матрица: 
 [[-250 -244 -239 ...  974  985  990]
 [-234 -223 -216 ...  987  992  995]
 [-229 -220 -193 ...  953  962  970]
 ...
 [-247 -238 -205 ...  982  990  998]
 [-243 -238 -220 ...  944  950  972]
 [-208 -207 -198 ...  962  985  994]]


In [239]:
#Отсчёт времени и вывод результатов турнирной сортировки
matrix_copy = array.copy()
start_time = time.time_ns() 
for i, s in enumerate(matrix_copy):
    matrix_copy[i] = turn(s)
elapsed_time = (time.time_ns() - start_time)
time_results.update(dict(Турнирная=elapsed_time))
print("Затраченное время = ", elapsed_time, "ns", "\n", "Преобразованная матрица:", "\n", matrix_copy)

Затраченное время =  55037800 ns 
 Преобразованная матрица: 
 [[-250 -244 -239 ...  974  985  990]
 [-234 -223 -216 ...  987  992  995]
 [-229 -220 -193 ...  953  962  970]
 ...
 [-247 -238 -205 ...  982  990  998]
 [-243 -238 -220 ...  944  950  972]
 [-208 -207 -198 ...  962  985  994]]


#### Вывод результатов затраченного времени:

In [240]:
for i, j in time_results.items():
    print(f"{i} - {j} ns")

Выбором - 265186600 ns
Обменом - 243176200 ns
Вставкой - 250175300 ns
Шелла - 229178100 ns
Пирамидальная - 45030300 ns
Быстрая - 18011600 ns
Турнирная - 55037800 ns
