## Лабортаорная работа №2


### Задание №1

   Реализовать методы поиска в соответствии с заданием. Организовать генерацию начального набора случайных данных. Для всех вариантов добавить реализацию добавления, поиска и удаления элементов. Оценить время работы каждого алгоритма поиска и сравнить его со временем работы стандартной функции поиска, используемой в выбранном языке программирования.

### Массив

In [56]:
import numpy as np
import random
import time

arr = np.random.randint(-100, 100, (15))
search_num = arr[random.randint(0, len(arr)-1)]
arr.sort()

print("Массив: ", arr)
print("Число, которое ищем: ", search_num)

Массив:  [-95 -94 -82 -54 -13  23  29  46  54  57  62  69  79  80  93]
Число, которое ищем:  -94


### Бинарный поиск

In [57]:
def binary_search(array, element):
    mid = 0
    start = 0
    end = len(array)
    step = 0
    
    while (start <= end):
        step+=1
        mid = (start + end) // 2
        if element == array[mid]:
            return mid 
        if element < array[mid]:
            end = mid - 1
        else:
            start = mid + 1
    return -1

### Бинарное дерево

In [58]:
class TreeNode:
    def __init__(self, value, left = None, right = None, parent = None):
        self.value = value
        self.leftChild = left
        self.rightChild = right
        self.parent = parent
    
    def hasLeftChild(self):
        return self.leftChild
    
    def hasRightChild(self):
        return self.rightChild
    
    def isLeftChild(self):
        return self.parent and self.parent.leftChild == self
    
    def isRightChild(self):
        return self.parent and self.parent.rightChild == self
    
    def isLeaf(self):
        return not (self.rightChild or self.leftChild)
    
    def hasBothChildren(self):
        return self.rightChild and self.leftChild
    
    
class BinaryTree:
    def __init__(self):
        self.root = None
        self.size = 0
    
    def length(self):
        return self.size
    
    def add(self, value):
        if self.root:
            self._add(value, self.root)
        else:
            self.root = TreeNode(value)
        self.size = self.size + 1
    
    
    
    def _add(self, value, currentNode):
        if value < currentNode.value:
            if currentNode.hasLeftChild():
                self._add(value, currentNode.leftChild)
            else:
                currentNode.leftChild = TreeNode(value, parent=currentNode)
        else:
            if currentNode.hasRightChild():
                self._add(value, currentNode.rightChild)
            else:
                currentNode.rightChild = TreeNode(value, parent=currentNode)

    
    def getItemNode(self, value, currentNode = None):
        if currentNode is None:
            currentNode = self.root
        if value < currentNode.value:
            if currentNode.hasLeftChild():
                return self.getItemNode(value, currentNode.leftChild)
            else:
                return None
        elif value > currentNode.value:
            if currentNode.hasRightChild():
                return self.getItemNode(value, currentNode.rightChild)
            else:
                return None
        else:
            return currentNode
    
    def isInTree(self, value):
        if self.getItemNode(value):
            print(value)
        else:
            print("Значение не найдено")
    
                    
    def insertList(self, arr):
        for i in arr:
            self.add(i)
            
    
    
def binarytree_search(tree, element):
    tree.isInTree(element)

tree = BinaryTree()
tree.insertList(arr)

### Фибоначчиев

In [59]:
def fibonacci_search(array, element):
    fi0 = 0
    fi1 = 1
    fi2 = fi0 + fi1
    while (fi2 < len(array)):
        fi0 = fi1
        fi1 = fi2
        fi2 = fi0 + fi1
    index = -1
    while (fi2 > 1):
        i = min(index + fi0, (len(array) - 1))
        if (array[i] < element):
            fi2 = fi1
            fi1 = fi0
            fi0 = fi2 - fi1
            index = i
        elif (array[i] > element):
            fi2 = fi0
            fi1 = fi1 - fi0
            fi0 = fi2 - fi1
        else:
            return i 
    if (fi1 and index < (len(array)-1) and array[index+1] == element):
        return index + 1
    return -1

### Интерполяционный

In [60]:
def interpolation_search(array, element):
    low = 0 
    high = len(array) - 1
    while low <= high and element >= array[low] and element <= array[high]:
        index = low + int(((float(high - low) / (array[high] - array [low])) * (element - array[low])))
        if array[index] == element:
            return index
        if array[index] < element:
            low = index + 1
        else:
            high = index - 1
    return -1

### Стандартный

In [61]:
def default_search(array, element):
    index = -1
    for i in range(len(array)):
        if array[i] == element:
            index = i;
    if index > 0:
        return index

In [62]:
#Для отсчёта времени 
def sorting_time(array, element, selectedSort):
    startTime = time.perf_counter()
    selectedSort(array, element)        
    return time.perf_counter() - startTime

In [63]:
print ("Индекс, найденный бинарным поиском: ", binary_search(arr, search_num), ", затраченное время: ", sorting_time(arr, search_num, binary_search))
print ("Индекс, найденный поиском Фибоначи: ", fibonacci_search(arr, search_num), ", затраченное время: ", sorting_time(arr, search_num, fibonacci_search))
print ("Индекс, найденный интерполяционным поиском: ", interpolation_search(arr, search_num), ", затраченное время: ", sorting_time(arr, search_num, interpolation_search))
print ("Индекс, найденный cтандартным поиском: ", default_search(arr, search_num), ", затраченное время: ", sorting_time(arr, search_num, default_search))

Индекс, найденный бинарным поиском:  1 , затраченное время:  4.00003045797348e-06
Индекс, найденный поиском Фибоначи:  1 , затраченное время:  3.999914042651653e-06
Индекс, найденный интерполяционным поиском:  1 , затраченное время:  9.899958968162537e-06
Индекс, найденный cтандартным поиском:  1 , затраченное время:  3.100023604929447e-06


### Задание №2

### Простое рехэширование 

In [64]:
class HashTable:  
    def __init__(self, size = 20):
        self.size = size
        self.data = [None for i in range(size)]
            
    def get_hash(self, key, i=0):
        return (hash(key) + i) % self.size
    
    def __getitem__(self, key):
        i = 0
        while True:
            index = self.get_hash(key, i)
            if self.data[index] is None or i == self.size:
                break
            if self.data[index][0] == key:
                return self.data[index][1]
            i += 1
    
    def __setitem__(self, key, value):
        i = 0
        while True:
            index = self.get_hash(key, i)
            if self.data[index] is None:
                self.data[index] = (key, value)
                break
            elif self.data[index] is not None and i != self.size:
                i += 1
                continue
            else:
                print("В таблице нет свободных ячеек")
                break 
        
    def __delitem__(self, key):
        i = 0
        while True:
            index = self.get_hash(key, i)
            if self.data[index][0] == key:
                self.data[index] = None
                print("Элемент {} удален".format(key))
                break
            elif self.data[index] is not None and i != self.size:
                i += 1
                continue
            else:
                print("Элемента {} нет в таблице".format(key))
                break

### Рехэширование  с помощью псевдослучайных чисел

In [65]:
class HashTableRand(HashTable):
    def get_hash(self, key, i=0):
        return (2 * hash(key) + i+2) % self.size

### Метод цеопчек

In [66]:
class HashTableChain(HashTable):
    def __init__(self, size = 20):
        self.size = size
        self.data = [[] for i in range(size)]
    
    def get_hash(self, key):
        return hash(key) % self.size
    
    def __getitem__(self, key):
        arr_index = self.get_hash(key)
        for kv in self.data[arr_index]:
            if kv[0] == key:
                return kv[1]
            
    def __setitem__(self, key, val):
        h = self.get_hash(key)
        found = False
        for idx, element in enumerate(self.data[h]):
            if len(element)==2 and element[0] == key:
                self.data[h][idx] = (key,val)
                found = True
        if not found:
            self.data[h].append((key,val))
        
    def __delitem__(self, key):
        arr_index = self.get_hash(key)
        for index, kv in enumerate(self.data[arr_index]):
            if kv[0] == key:
                print("Элемент {} удален".format(key))
                del self.data[arr_index][index]

In [67]:
def element_search(table, key):
    startTime = time.perf_counter()
    table[key]        
    return time.perf_counter() - startTime

def fillHashTable(arr, arrStr, table):
    for i in range(len(arrStr)):
        table[arr[i]] = arrStr[i]

### Инициализация и вывод результатов 

In [68]:
standartHash = HashTable()
randHash = HashTableRand()
chainHash = HashTableRand()

ar = [-1, 231, 441, 50, 14, 1, 6, 8, -123, 41]
arrStr = ["a", "b", "c", "d", "e", "f", "g"]
searchNum = 231

fillHashTable(ar, arrStr, standartHash)
fillHashTable(ar, arrStr, randHash)
fillHashTable(ar, arrStr, chainHash)

print("Простое рехэширование: ", element_search(standartHash, searchNum))
print("Псевдослучайное рехэширование: ", element_search(randHash, searchNum))
print("Метод цепочек: ", element_search(chainHash, searchNum))

Простое рехэширование:  4.500034265220165e-06
Псевдослучайное рехэширование:  5.499925464391708e-06
Метод цепочек:  4.100031219422817e-06


### Задание № 3

Расставить на стандартной 64-клеточной шахматной доске 8 ферзей так, чтобы ни один из них не находился под боем другого». Подразумевается, что ферзь бьёт все клетки, расположенные по вертикалям, горизонталям и обеим диагоналям
Написать программу,  которая находит хотя бы один способ решения задач.


Мат. формулировка: заполнить матрицу размером 8 x 8 нулями и единицами таким образом, чтобы сумма всех элементов матрицы была равна 8, при этом сумма элементов ни в одном столбце, строке или диагональном ряде матрицы не превышала единицы

In [69]:
#Создание пустой доски 
n = 8
board = np.zeros((n, n))
counter = 0

#Функция для установки ферзя
def setQueen(i, j):
    for x in range(n):
        board[x][j] += 1
        board[i][x] += 1
        if 0 <= i + j - x < 8:
            board [i + j - x][x] += 1
        if 0 <= i - j + x < 8:
            board [i - j + x][x] += 1
    board [i][j] = -1

#Функция для удаления ферзя
def removeQueen(i, j):
    for x in range(n):
        board[x][j] -= 1
        board[i][x] -= 1
        if 0 <= i + j - x < 8:
            board [i + j - x][x] -= 1
        if 0 <= i - j + x < 8:
            board [i - j + x][x] -= 1
    board [i][j] = 0 

#Функция, для вывода
def print_result():
    global counter
    counter += 1 
    board_to_print = board.copy()
    for i in range (n):
        for j in range (n):
            if board_to_print[i][j] != -1: 
                board_to_print[i][j] = 0
    print("Результат №", counter)
    print(board_to_print)
    
def solution(i):
    for j in range(n):
        if board[i][j] == 0:
            setQueen(i, j)
            if i == 7:
                print_result()
            else:
                solution(i + 1)
            removeQueen(i, j)

solution(0)
print ("Общее число результатов: ", counter)

Результат № 1
[[-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]]
Результат № 2
[[-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]]
Результат № 3
[[-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]]
Результат № 4
[[-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  

Результат № 81
[[ 0.  0.  0.  0.  0.  0. -1.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]]
Результат № 82
[[ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]]
Результат № 83
[[ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]]
Результат № 84
[[ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  